# SPDX-FileCopyrightText: 2019 Nicholas Tollervey, written for Adafruit Industries

# SPDX-License-Identifier: MIT

name: Release Actions

on:
  release:
    types: [published]

jobs:
  upload-pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check For setup.py
      id: need-pypi
      run: |
        echo ::set-output name=setup-py::$( find . -wholename './setup.py' )
    - name: Set up Python
      if: contains(steps.need-pypi.outputs.setup-py, 'setup.py')
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      if: contains(steps.need-pypi.outputs.setup-py, 'setup.py')
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_PASSWORD: ${{ secrets.PYPI_UPLOAD_TOKEN }}
      run: |
        bash tools/build.sh
